Fix call-abi-compatibility.ll error
Commit af855a787d1d9aa5bac14cac3853ae31eb0ec283 introduces a broken test
case causing an error,
  error: instruction expected to be numbered '%1'